### ISSUE TITLE
Connect has been rewritten to not use setState

### ISSUE THREAD

**Issue by thewillhuang** [procore/redux-modules#117]
https://github.com/reactjs/react-redux/pull/416

should we use react-redux's connect?

**Comment by wtgtybhertgeghgtwtg** [comment]
I have preliminary work on it done, but I'm holding off until #107.  I won't complain if somebody else gets it done first, though.

**Comment by mboperator** [comment]
I'm thinking we should move back to including `react-redux` as a `peerDependency` and have `connectModule` build upon the new `connectAdvanced` api.

Since we're mainly using `connectModule` to register reducers and simply bind the dispatch there's no need to bring in all the complexity of the `react-redux` library just to save a few kilobytes on the module size.
